### ISSUE TITLE
Library stopped working after updating exoplayer in my project to 2.17.1

### ISSUE THREAD

**Issue by qwaskhaled** [a914-gowtham/android-video-trimmer#74]
Fatal Exception: java.lang.NoClassDefFoundError
Failed resolution of: Lcom/google/android/exoplayer2/Player$EventListener;

**Comment by a914-gowtham** [comment]
Hi @qwaskhaled  Updated in the latest v[1.7.2](https://github.com/a914-gowtham/android-video-trimmer/releases/tag/1.7.2) version.

**Comment by a914-gowtham** [comment]
feel free to reopen it. if you get the issue again
